server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5422/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ACCOUNT-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone : http://localhost:8761/eureka



